project:
  type: website
  resources:
    - data/*.json
    - data/*.csv
    - tobacco-chart.js
    - states-chart.js

website:
  title: "CVD Predictors"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



